# Generated by Django 6.0 on 2025-12-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
